spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis-plus:
  global-config:
    refresh: false
  mapper-locations: classpath*:mybatis/*.xml
logging:
  config: classpath:config/logback.xml
