mybatis-plus:
  global-config:
    refresh: false
  mapper-locations: classpath*:mybatis/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      username: root
      password: root
